openapi: '3.0.3'
info:
  title: Vehicle API documentation
  version: 1.0.0
servers:
  - url: 'localhost:50572/api/v1'
paths:
  /vehicles/{id}:
    get:
      summary: request a vehicle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 507f191e810c19729de860ea # 24 long string
          description: ID of the vehicle
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    required:
                      [
                        _id,
                        manufacturer,
                        model,
                        fuel,
                        type,
                        color,
                        VIN,
                        VRM,
                        used,
                        modelYear,
                        createdAt,
                        updatedAt,
                      ]
                    properties:
                      _id:
                        type: string
                        description: The Vehicle ID.
                        example: 507f191e810c19729de860ea
                      manufacturer:
                        type: string
                        example: Toyota
                      model:
                        type: string
                        example: Camry
                      fuel:
                        type: string
                        example: gas
                      type:
                        type: string
                        example: sedan
                      color:
                        type: string
                        example: white
                      VIN:
                        type: string
                        example: TNRU392EESIR93ERF
                      VRM:
                        type: string
                        example: M3EN49A
                      used:
                        type: boolean
                        example: true
                      modelYear:
                        type: number
                        example: 2000
                      createdAt:
                        type: string
                        example: 2022-02-26T16:37:48.244Z
                      updatedAt:
                        type: string
                        example: 2022-02-26T16:37:48.307Z

        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'request body is not required for GET method'

        '404':
          description: 'Not found'
        '500':
          description: 'Internal Server Error'

    patch:
      summary: patch a vehicle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 507f191e810c19729de860ea # 24 long string
          description: ID of the vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                manufacturer:
                  type: string
                  example: Toyota
                model:
                  type: string
                  example: Camry
                fuel:
                  type: string
                  example: gas
                type:
                  type: string
                  example: sedan
                color:
                  type: string
                  example: white
                VIN:
                  type: string
                  example: TNRU392EESIR93ERF
                VRM:
                  type: string
                  example: M3EN49A
                used:
                  type: boolean
                  example: true
                modelYear:
                  type: number
                  example: 2000

      responses:
        '204':
          description: 'No content:'
        '400':
          description: 'Bad request'
        '404':
          description: 'Not found'
        '415':
          description: 'Unsupported Media Type'
        '422':
          description: 'Unprocessable Content'
        '500':
          description: 'Internal Server Error'

    delete:
      summary: delete a vehicle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: 507f191e810c19729de860ea # 24 long string
          description: ID of the vehicle
      responses:
        '204':
          description: 'No content:'
        '400':
          description: 'Bad request'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'request body is not required for DELETE method'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal Server Error'

  /vehicles:
    post:
      summary: create a new vehicle
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [manufacturer, model, fuel, type, color, VIN, VRM, used, modelYear]
              properties:
                manufacturer:
                  type: string
                  example: Toyota
                model:
                  type: string
                  example: Camry
                fuel:
                  type: string
                  example: gas
                type:
                  type: string
                  example: sedan
                color:
                  type: string
                  example: white
                VIN:
                  type: string
                  example: TNRU392EESIR93ERF
                VRM:
                  type: string
                  example: M3EN49A
                used:
                  type: boolean
                  example: true
                modelYear:
                  type: number
                  example: 2000

      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: The Vehicle ID.
                        example: 507f191e810c19729de860ea
                      manufacturer:
                        type: string
                        example: Toyota
                      model:
                        type: string
                        example: Camry
                      fuel:
                        type: string
                        example: gas
                      type:
                        type: string
                        example: sedan
                      color:
                        type: string
                        example: white
                      VIN:
                        type: string
                        example: TNRU392EESIR93ERF
                      VRM:
                        type: string
                        example: M3EN49A
                      used:
                        type: boolean
                        example: true
                      modelYear:
                        type: number
                        example: 2000
                      createdAt:
                        type: string
                        example: 2022-02-26T16:37:48.244Z
        '400':
          description: 'Bad request'
        '404':
          description: 'Not found'
        '415':
          description: 'Unsupported Media Type'
        '422':
          description: 'Unprocessable Content'
        '500':
          description: 'Internal Server Error'
